name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed
        
jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
     
      - name: Deploy image
        # if: ${{ github.ref_name == 'main' }}
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPOSITORY: ${{ github.repository }}
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PWD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -DskipTests=true spring-boot:build-image
