name: labeler

on: [pull_request]
        
jobs:
  labeler:
    runs-on: ubuntu-20.04
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fail_if_xl: 'true'
